language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd TraceGerm/TraceGermApp/TraceGerm/www
script:
  ./node_modules/.bin/karma start --browsers Firefox --single-run
