language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd TraceGerm
script:
