language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g karma-cli
  - cd TraceGerm/www
script:
  karma start TraceGerm.conf.js
